eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 106.52.213.64
    port: 5672
    username: guest
    password: guest
  datasource:
    name: dev
    url: jdbc:mysql://106.52.213.64:3306/snailmall
    username: root
    password: root
redis:
    host: 106.52.213.64
    port: 6379
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000
